# -*- coding: utf-8 -*-
"""SCT_DS_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQ0Q8m5VBj5OkMZeZlvTtzdu5XG-sero
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

np.random.seed(42)

# Generate data
n_accidents = 5000
hour_probs = np.array([0.02, 0.01, 0.01, 0.01, 0.02, 0.03, 0.05, 0.08, 0.10, 0.08, 0.06, 0.05, 0.04, 0.04, 0.05, 0.07, 0.09, 0.08, 0.06, 0.04, 0.03, 0.03, 0.02, 0.02])
hour_probs = hour_probs / hour_probs.sum()

hours = np.random.choice(range(0, 24), n_accidents, p=hour_probs)
days = np.random.choice(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'], n_accidents, p=[0.18, 0.18, 0.17, 0.17, 0.17, 0.08, 0.05])
severity = np.random.choice(['Minor', 'Moderate', 'Severe'], n_accidents, p=[0.60, 0.30, 0.10])
weather = np.random.choice(['Clear', 'Rainy', 'Foggy', 'Snowy'], n_accidents, p=[0.70, 0.15, 0.10, 0.05])
road_type = np.random.choice(['Highway', 'Urban', 'Rural'], n_accidents, p=[0.40, 0.45, 0.15])
speed_limit = np.random.choice([25, 35, 45, 55, 65, 75], n_accidents, p=[0.15, 0.20, 0.25, 0.20, 0.15, 0.05])

df = pd.DataFrame({
    'Hour': hours,
    'Day': days,
    'Severity': severity,
    'Weather': weather,
    'Road_Type': road_type,
    'Speed_Limit': speed_limit
})

# Print analysis
print("=" * 60)
print("TRAFFIC ACCIDENT ANALYSIS")
print("=" * 60)
print(f"\nTotal accidents: {len(df)}")
print(f"\nSeverity Distribution:")
for sev, count in df['Severity'].value_counts().items():
    print(f"  {sev}: {count} ({count/len(df)*100:.1f}%)")

print(f"\nTop 5 Peak Hours:")
for hour, count in df['Hour'].value_counts().sort_index().nlargest(5).items():
    print(f"  {hour:02d}:00 - {hour+1:02d}:00: {count} ({count/len(df)*100:.1f}%)")

print(f"\nAccidents by Day:")
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
for day, count in df['Day'].value_counts().reindex(day_order).items():
    print(f"  {day}: {count} ({count/len(df)*100:.1f}%)")

print(f"\nSevere Accidents by Weather:")
for weather in df['Weather'].unique():
    severe = len(df[(df['Weather'] == weather) & (df['Severity'] == 'Severe')])
    total = len(df[df['Weather'] == weather])
    print(f"  {weather}: {severe}/{total} ({severe/total*100:.1f}%)")

# Visualize
fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.suptitle('Traffic Accident Analysis Dashboard', fontsize=16, fontweight='bold')

# Hourly
ax = axes[0, 0]
hourly = df['Hour'].value_counts().sort_index()
ax.bar(hourly.index, hourly.values, color='#FF6B6B', edgecolor='black')
ax.set_xlabel('Hour of Day')
ax.set_ylabel('Accidents')
ax.set_title('Accidents by Hour')
ax.grid(axis='y', alpha=0.3)

# Severity
ax = axes[0, 1]
severity_data = df['Severity'].value_counts()
ax.pie(severity_data.values, labels=severity_data.index, autopct='%1.1f%%', colors=['#4CAF50', '#FFC107', '#F44336'])
ax.set_title('Severity Distribution')

# Day of week
ax = axes[0, 2]
day_data = df['Day'].value_counts().reindex(day_order)
ax.bar(range(len(day_data)), day_data.values, color='#2196F3', edgecolor='black')
ax.set_xticks(range(len(day_data)))
ax.set_xticklabels([d[:3] for d in day_data.index], rotation=45)
ax.set_ylabel('Accidents')
ax.set_title('Accidents by Day')
ax.grid(axis='y', alpha=0.3)

# Weather
ax = axes[1, 0]
weather_data = df['Weather'].value_counts()
ax.barh(weather_data.index, weather_data.values, color='#9C27B0', edgecolor='black')
ax.set_xlabel('Accidents')
ax.set_title('Accidents by Weather')
ax.grid(axis='x', alpha=0.3)

# Road type
ax = axes[1, 1]
road_data = df['Road_Type'].value_counts()
ax.bar(road_data.index, road_data.values, color=['#FF9800', '#00BCD4', '#8BC34A'], edgecolor='black')
ax.set_ylabel('Accidents')
ax.set_title('Accidents by Road Type')
ax.grid(axis='y', alpha=0.3)

# Heatmap
ax = axes[1, 2]
heatmap = pd.crosstab(df['Severity'], df['Weather'])
sns.heatmap(heatmap, annot=True, fmt='d', cmap='YlOrRd', ax=ax, cbar_kws={'label': 'Count'})
ax.set_title('Severity vs Weather')
ax.set_xlabel('Weather')
ax.set_ylabel('Severity')

plt.tight_layout()
plt.savefig('traffic_accident_dashboard.png', dpi=300, bbox_inches='tight')
df.to_csv('traffic_accident_data.csv', index=False)

print("\n✓ Saved: traffic_accident_dashboard.png")
print("✓ Saved: traffic_accident_data.csv")